#!/usr/bin/env bash
# Build the Nexus desktop installer on Arch Linux.
#
# ONE COMMAND, ZERO PREREQUISITES. On a clean Arch install this script:
#
#   1. Installs system deps via pacman (python, pnpm, rust, base-devel)
#   2. Creates packages/server/.venv if missing
#   3. Installs the three local monorepo Python packages
#   4. PyInstaller-bundles the backend into a single Linux binary
#   5. Stages the binary for the Tauri sidecar
#   6. pnpm install + build frontend
#   7. Tauri build → produces AppImage / .deb / .rpm
#
# Idempotent: re-running after a code change only rebuilds what changed.
#
# Usage:
#   ./scripts/build-arch.sh                  # default — bootstrap + build
#   ./scripts/build-arch.sh --clean          # nuke caches first
#   DESKTOP_VERSION_OVERRIDE=0.1.18 ./scripts/build-arch.sh
#
# Output:
#   src-tauri/target/release/bundle/appimage/Nexus_*.AppImage
#   src-tauri/target/release/bundle/deb/*.deb
#   src-tauri/target/release/bundle/rpm/*.rpm

set -euo pipefail

DESKTOP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$DESKTOP_ROOT/../.." && pwd)"
SERVER_ROOT="$REPO_ROOT/packages/server"
VENV="$SERVER_ROOT/.venv"

# ── Flags ─────────────────────────────────────────────────────────────
CLEAN=false
for arg in "$@"; do
  case "$arg" in
    --clean) CLEAN=true ;;
    -h|--help)
      sed -n '2,/^set/p' "$0"
      exit 0
      ;;
  esac
done

# ── Pretty printing ───────────────────────────────────────────────────
say() { printf "\033[1;34m▶\033[0m %s\n" "$*"; }
ok()  { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn(){ printf "\033[1;33m⚠\033[0m %s\n" "$*"; }
die() { printf "\033[1;31m✗ %s\033[0m\n" "$*" >&2; exit 1; }
step() { echo; printf "\033[1m── %s ──\033[0m\n" "$*"; }

# ── Sanity ────────────────────────────────────────────────────────────
[ "$(uname -m)" = "x86_64" ] || die "this script only supports x86_64 Linux"
TARGET_TRIPLE="x86_64-unknown-linux-gnu"
say "host: $TARGET_TRIPLE"

# ── Bootstrap system prerequisites ────────────────────────────────────
step "Checking system prerequisites"

need_pacman=()
for pkg in base-devel python python-pip python-virtualenv pnpm rust cargo webkit2gtk-4.1 libsoup3 openssl; do
  if ! pacman -Q "$pkg" >/dev/null 2>&1; then
    need_pacman+=("$pkg")
  fi
done

if [ "${#need_pacman[@]}" -gt 0 ]; then
  say "Installing missing packages via pacman: ${need_pacman[*]}"
  sudo pacman -S --needed --noconfirm "${need_pacman[@]}"
fi
ok "system prerequisites satisfied"

# ── Build identity ────────────────────────────────────────────────────
# Format: MAJOR.MINOR.PATCH+<utc-timestamp>.<git-sha>[-dirty]
NEXUS_PACKAGE_VERSION="$(node -p "require('$DESKTOP_ROOT/package.json').version" 2>/dev/null || echo "0.0.0")"
NEXUS_GIT_COMMIT_COUNT="$(cd "$REPO_ROOT" && git rev-list --count HEAD 2>/dev/null || echo "0")"
NEXUS_VERSION="$(echo "$NEXUS_PACKAGE_VERSION" \
  | awk -F. -v p="$NEXUS_GIT_COMMIT_COUNT" '{
      major = ($1 == "" ? "0" : $1)
      minor = ($2 == "" ? "0" : $2)
      print major "." minor "." p
    }')"
NEXUS_BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
NEXUS_BUILD_TIME_COMPACT="$(date -u +%Y%m%dT%H%M%SZ)"
NEXUS_GIT_SHA="$(cd "$REPO_ROOT" && git rev-parse --short=7 HEAD 2>/dev/null || echo nogit)"
NEXUS_GIT_DIRTY=""
if cd "$REPO_ROOT" && ! git diff --quiet 2>/dev/null; then
  NEXUS_GIT_DIRTY="-dirty"
fi
NEXUS_BUILD_ID="${NEXUS_VERSION}+${NEXUS_BUILD_TIME_COMPACT}.${NEXUS_GIT_SHA}${NEXUS_GIT_DIRTY}"
export NEXUS_VERSION NEXUS_BUILD_ID NEXUS_BUILD_TIME NEXUS_GIT_SHA

printf "\n\033[1;36m"
printf "═══════════════════════════════════════════════════════════════════════\n"
printf "  Nexus build %s\n" "$NEXUS_BUILD_ID"
printf "  version:  %s   (package.json: %s  →  patch = git commits)\n" \
       "$NEXUS_VERSION" "$NEXUS_PACKAGE_VERSION"
printf "  commits:  %s   git:      %s%s\n" \
       "$NEXUS_GIT_COMMIT_COUNT" "$NEXUS_GIT_SHA" "$NEXUS_GIT_DIRTY"
printf "  built at: %s\n" "$NEXUS_BUILD_TIME"
printf "═══════════════════════════════════════════════════════════════════════\n"
printf "\033[0m\n"

# Stamp __build_info__.py
cat > "$SERVER_ROOT/nexus_server/__build_info__.py" <<EOF
# AUTO-GENERATED by scripts/build-arch.sh — do not edit by hand.
VERSION    = "$NEXUS_VERSION"
BUILD_ID   = "$NEXUS_BUILD_ID"
BUILD_TIME = "$NEXUS_BUILD_TIME"
GIT_SHA    = "$NEXUS_GIT_SHA$NEXUS_GIT_DIRTY"
EOF
ok "stamped __build_info__.py with v$NEXUS_BUILD_ID"

# ── --clean: wipe caches first ────────────────────────────────────────
if [ "$CLEAN" = true ]; then
  step "Cleaning caches"
  rm -rf "$SERVER_ROOT/build" "$SERVER_ROOT/dist"
  rm -rf "$DESKTOP_ROOT/node_modules" "$DESKTOP_ROOT/pnpm-lock.yaml"
  rm -rf "$DESKTOP_ROOT/src-tauri/target"
  rm -f  "$DESKTOP_ROOT/src-tauri/binaries/nexus-server-"*
  ok "caches cleaned"
fi

# ═════════════════════════════════════════════════════════════════════
# Stage 2: Python venv + install local sibling packages
# ═════════════════════════════════════════════════════════════════════
step "Python venv + monorepo deps"

if [ ! -d "$VENV" ]; then
  say "creating venv at $VENV"
  python -m venv "$VENV"
fi
ok "venv ready"

# shellcheck disable=SC1091
source "$VENV/bin/activate"
ok "using python $(python --version) at $(which python)"

say "upgrading pip"
python -m pip install --upgrade pip >/dev/null 2>&1 || true
say "installing pyinstaller"
python -m pip install "pyinstaller>=6.0" >/dev/null 2>&1 || die "pip install pyinstaller failed"

SIBLINGS=(
  "$REPO_ROOT/packages/sdk"     # nexus-core
  "$REPO_ROOT/packages/nexus"   # nexus
  "$SERVER_ROOT"                # nexus-server
)
for sibling in "${SIBLINGS[@]}"; do
  name="$(basename "$sibling")"
  say "installing $name"
  python -m pip install -e "$sibling" >/dev/null 2>&1 || die "pip install -e $name failed"
done
ok "monorepo packages in sync"

# ═════════════════════════════════════════════════════════════════════
# Stage 3: PyInstaller — bundle the backend
# ═════════════════════════════════════════════════════════════════════
step "PyInstaller: backend → single binary"

BINARY_NAME="nexus-server-$TARGET_TRIPLE"
BINARY_OUT="$SERVER_ROOT/dist/$BINARY_NAME"

pushd "$SERVER_ROOT" >/dev/null
rm -rf build/ dist/
python -m PyInstaller nexus-server.spec --clean --noconfirm 2>&1 | tail -15
[ -f "$BINARY_OUT" ] || die "PyInstaller did not produce $BINARY_OUT"
ok "backend binary: $BINARY_OUT ($(du -h "$BINARY_OUT" | cut -f1))"
popd >/dev/null

# Stage the binary for Tauri
STAGED_BIN="$DESKTOP_ROOT/src-tauri/binaries/$BINARY_NAME"
mkdir -p "$DESKTOP_ROOT/src-tauri/binaries"
mkdir -p "$DESKTOP_ROOT/src-tauri/resources"
cp "$BINARY_OUT" "$STAGED_BIN"
chmod +x "$STAGED_BIN"
ok "binary staged at src-tauri/binaries/$BINARY_NAME"

# ═════════════════════════════════════════════════════════════════════
# Stage 4: pnpm install + Tauri build
# ═════════════════════════════════════════════════════════════════════
step "Frontend: pnpm deps + Tauri build"
pushd "$DESKTOP_ROOT" >/dev/null

say "pnpm install"
pnpm install 2>&1 | tail -8 || warn "install had warnings (continuing)"

say "generating Tauri icons"
pnpm icons 2>&1 | tail -3 || warn "icons step had warnings (ok if files exist)"

# Bundle default.env if packages/server/.env exists
SERVER_DOTENV="$SERVER_ROOT/.env"
BUNDLE_DEFAULT_ENV="$DESKTOP_ROOT/src-tauri/resources/default.env"
if [ -f "$SERVER_DOTENV" ]; then
  {
    cat <<EOF
# Nexus default environment — BUNDLED INTO THE INSTALLER
# Auto-regenerated by scripts/build-arch.sh on $NEXUS_BUILD_TIME
# Source: packages/server/.env
EOF
    while IFS='' read -r line || [[ -n "$line" ]]; do
      case "$line" in
        SERVER_HOST=*|SERVER_PORT=*|SERVER_SECRET=*) continue ;;
        DATABASE_URL=*) continue ;;
        SERVER_PRIVATE_KEY=*) continue ;;
        ENVIRONMENT=*|LOG_LEVEL=*) continue ;;
        CORS_ALLOW_ORIGINS=*) continue ;;
        GEMINI_API_KEY=*)    echo "GEMINI_API_KEY="    ; continue ;;
        OPENAI_API_KEY=*)    echo "OPENAI_API_KEY="    ; continue ;;
        ANTHROPIC_API_KEY=*) echo "ANTHROPIC_API_KEY=" ; continue ;;
        TAVILY_API_KEY=*)    echo "TAVILY_API_KEY="    ; continue ;;
        JINA_API_KEY=*)      echo "JINA_API_KEY="      ; continue ;;
      esac
      echo "$line"
    done < "$SERVER_DOTENV"
  } > "$BUNDLE_DEFAULT_ENV"
  ok "wrote src-tauri/resources/default.env"
fi

# Bump version before build
node scripts/bump-version.mjs

say "Tauri build — AppImage / deb / rpm (cold compile: 5-10 min)"
export VITE_NEXUS_BUILD_ID="$NEXUS_BUILD_ID"
export VITE_NEXUS_VERSION="$NEXUS_VERSION"
export VITE_NEXUS_GIT_SHA="$NEXUS_GIT_SHA$NEXUS_GIT_DIRTY"
export VITE_NEXUS_BUILD_TIME="$NEXUS_BUILD_TIME"
export NEXUS_BUILD_ID NEXUS_VERSION NEXUS_GIT_SHA NEXUS_BUILD_TIME

pnpm tauri build 2>&1 | tail -20

# ═════════════════════════════════════════════════════════════════════
# Done
# ═════════════════════════════════════════════════════════════════════
step "Build complete"
echo
BUNDLE_DIR="$DESKTOP_ROOT/src-tauri/target/release/bundle"
for d in appimage deb rpm; do
  if [ -d "$BUNDLE_DIR/$d" ]; then
    files=("$BUNDLE_DIR/$d"/*)
    if [ -e "${files[0]}" ]; then
      ok "$d package(s):"
      ls -1 "$BUNDLE_DIR/$d"/* | sed 's|^|    |'
    fi
  fi
done
echo
warn "unsigned build — AppImage needs chmod +x; .deb/.rpm need trust on first install"
popd >/dev/null
