#!/usr/bin/env node
/**
 * Auto-bump the desktop's patch version BEFORE every `pnpm tauri build`.
 *
 * Why
 * ---
 * Tauri's macOS dmg-bundle refuses to overwrite an existing .dmg with
 * the same version. The .app bundle is also keyed by version in
 * Info.plist; Finder refuses to install when the user's installed
 * version >= the new one. And we (+ the medic) need a quick visual
 * signal that "this dmg IS the build with the fix" — without scrolling
 * through commit hashes.
 *
 * What this script does
 * ---------------------
 * On every invocation:
 *   1. Read current version from packages/desktop-v2/package.json
 *      (the source of truth for the desktop bundle).
 *   2. Bump the PATCH component:  0.1.0 -> 0.1.1, 0.1.99 -> 0.1.100
 *      (we don't auto-bump minor/major; we do those by hand at
 *      intentional release boundaries.)
 *   3. Write the new version into the three places Tauri reads it:
 *        - packages/desktop-v2/package.json            "version"
 *        - packages/desktop-v2/src-tauri/tauri.conf.json "version"
 *        - packages/desktop-v2/src-tauri/Cargo.toml    [package] version
 *   4. Regenerate packages/desktop-v2/src/lib/build-info.ts so the
 *      LoginView footer + log lines always carry the new version + an
 *      ISO build timestamp. Medic can screenshot "v0.1.7 - 2026-06-28T..."
 *      to confirm they ran the latest dmg.
 *
 * Override
 * --------
 * Set DESKTOP_VERSION_OVERRIDE="X.Y.Z" to pin an exact version (e.g.
 * for a tagged release). The script writes it verbatim, no auto-bump.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const PKG_JSON   = resolve(ROOT, 'package.json');
const TAURI_JSON = resolve(ROOT, 'src-tauri/tauri.conf.json');
const CARGO_TOML = resolve(ROOT, 'src-tauri/Cargo.toml');
const BUILD_INFO = resolve(ROOT, 'src/lib/build-info.ts');

function parseSemver(s) {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(String(s || '').trim());
  if (!m) throw new Error(`unparseable version: ${s}`);
  return { major: +m[1], minor: +m[2], patch: +m[3] };
}

function fmt({ major, minor, patch }) {
  return `${major}.${minor}.${patch}`;
}

const pkg = JSON.parse(readFileSync(PKG_JSON, 'utf8'));
const current = pkg.version;

let next;
if (process.env.DESKTOP_VERSION_OVERRIDE) {
  parseSemver(process.env.DESKTOP_VERSION_OVERRIDE);  // validate
  next = process.env.DESKTOP_VERSION_OVERRIDE.trim();
  console.log(`[bump-version] override -> ${next}`);
} else {
  const v = parseSemver(current);
  v.patch += 1;
  next = fmt(v);
  console.log(`[bump-version] ${current} -> ${next}`);
}

// --- package.json -----------------------------------------------------
pkg.version = next;
writeFileSync(PKG_JSON, JSON.stringify(pkg, null, 2) + '\n', 'utf8');

// --- tauri.conf.json --------------------------------------------------
const tauri = JSON.parse(readFileSync(TAURI_JSON, 'utf8'));
tauri.version = next;
writeFileSync(TAURI_JSON, JSON.stringify(tauri, null, 2) + '\n', 'utf8');

// --- src-tauri/Cargo.toml ---------------------------------------------
let cargo = readFileSync(CARGO_TOML, 'utf8');
// Replace only the [package] section's version line, not workspace
// dependency version fields elsewhere in the file.
const cargoVersionRe = /(^\[package\][\s\S]*?\nversion\s*=\s*")[^"]*(")/m;
if (!cargoVersionRe.test(cargo)) {
  throw new Error('Cargo.toml has no [package] version = "..." line');
}
cargo = cargo.replace(cargoVersionRe, `$1${next}$2`);
writeFileSync(CARGO_TOML, cargo, 'utf8');

// --- src/lib/build-info.ts (desktop-side runtime constant) ------------
// LoginView footer reads BUILD_ID. Build timestamp here too gives the
// medic an unambiguous "fresh dmg or not?" signal in screenshots.
const now = new Date();
const iso = now.toISOString();
// Try to capture a short git sha so main.tsx can print it.
import { execSync } from 'child_process';
let gitSha = '';
try {
  gitSha = execSync('git rev-parse --short HEAD', {
    cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'],
  }).toString().trim();
} catch { /* no git OR detached / non-repo, leave empty */ }

const buildInfo =
`// AUTO-GENERATED by scripts/bump-version.mjs. Do NOT edit by hand.
// Updates on every \`pnpm tauri:build\` (the script bumps the patch
// component first). See scripts/bump-version.mjs for the
// DESKTOP_VERSION_OVERRIDE env var used for tagged releases.
export const BUILD_ID = '${next}';
export const BUILD_TS = '${iso}';
// Legacy aliases — main.tsx + a couple of other consumers reach for
// these names. Keep the names stable so we don't have to touch every
// log site on every build.
export const BUILD_TIME = BUILD_TS;
export const GIT_SHA = '${gitSha}';
// Convenience constant for log lines / about box.
export const BUILD_STAMP = \`v\${BUILD_ID} · \${BUILD_TS}\`;
`;
mkdirSync(dirname(BUILD_INFO), { recursive: true });
writeFileSync(BUILD_INFO, buildInfo, 'utf8');

console.log(`[bump-version] wrote v${next} (build ${iso})`);
