# AUTO-GENERATED by scripts/build-macos.sh — do not edit by hand.
# This file gets regenerated on every build and committed-as-default
# stays at the "dev" placeholder.
VERSION    = "0.1.53"
BUILD_ID   = "0.1.53+20260711T152059Z.e6026b6-dirty"
BUILD_TIME = "2026-07-11T15:20:59Z"
GIT_SHA    = "e6026b6-dirty"
