# AUTO-GENERATED by scripts/build-macos.sh — do not edit by hand.
# This file gets regenerated on every build and committed-as-default
# stays at the "dev" placeholder.
VERSION    = "0.1.57"
BUILD_ID   = "0.1.57+20260711T154956Z.0344623"
BUILD_TIME = "2026-07-11T15:49:56Z"
GIT_SHA    = "0344623"
