# AUTO-GENERATED by scripts/build-macos.sh — do not edit by hand.
# This file gets regenerated on every build and committed-as-default
# stays at the "dev" placeholder.
VERSION    = "0.1.47"
BUILD_ID   = "0.1.47+20260711T131827Z.2041dc4"
BUILD_TIME = "2026-07-11T13:18:27Z"
GIT_SHA    = "2041dc4"
