"""Validation-gated skill evolution — #119 (A+B+C).

Implements the SkillOpt (Microsoft / SJTU / Tongji / Fudan, May 2026)
core primitives, scoped down to what makes sense for a desktop
product:

  A. **Validation gate (the killer feature).** Each candidate edit is
     applied to a fresh copy of the SKILL.md, scored on a held-out
     example set, and accepted ONLY if it strictly beats the current
     best. Ties reject. This turns "let an LLM rewrite my prompt"
     from a coin flip into a monotonic-improvement process.

  B. **Protected durable region + rejected-edit buffer.** Authors
     wrap durable rules in ``<!-- nexus:durable -->`` fences;
     evolution can never touch them. Rejected proposals are
     persisted to ``.rejected.jsonl`` so future evolve runs don't
     repropose the same dead-ends.

  C. **Optimizer/target model split.** The skill executes (during
     scoring) with its declared ``model``; proposals are generated by
     ``optimizer_model`` if present (typically a stronger frontier
     model). Inference cost stays low; one-time evolve gets the smart
     model "for free".

Deliberately NOT implemented (per SkillOpt analysis):

  * Multi-epoch / minibatch / LR schedule machinery — at our scale
    the gate matters orders of magnitude more than the schedule.
  * Hidden optimizer-side meta-skill — visible artifacts only,
    consistent with our cognition-panel philosophy.

Public surface
==============
* :func:`evolve_skill_once` — propose → score candidates → return
  the best accepted edit (or the unchanged skill).
* :func:`evolve_skill_loop` — call ``evolve_skill_once`` until no
  more improvement OR ``max_iterations`` reached.
* :func:`score_skill_on_examples` — average judge-rubric score
  across the held-out examples.

All exposed via the ``evolve_skill`` agent tool (see
``tools_evolve.py``) and the ``/api/v1/skills/{name}/evolve`` HTTP
endpoint.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# Data shapes
# ─────────────────────────────────────────────────────────────────────


@dataclass
class TaskExample:
    """One held-out example. ``input`` is what gets passed to the
    skill's delegate call; ``rubric`` is the short text passed to
    the judge so it knows what "good" looks like. Keep both small
    — these end up multiplied by the number of rollouts and edits.
    """
    input: str
    rubric: str = ""
    # Optional reference: if you have an expected output, including
    # it lets the judge do diff-style scoring instead of pure rubric.
    expected_output_summary: str = ""
    # #131 — vision-grounded evolution. When the example carries
    # image bytes (e.g. a CT slice that the agent will re-read),
    # they're passed to both the rollout AND the judge so vision-
    # capable models see what the agent saw. Shape per entry:
    # {"mime": "image/png", "data_b64": "..."}. Empty list ⇒
    # pure-text example (current behaviour).
    images: list[dict] = field(default_factory=list)
    # #131 — when this example came from a medic correction
    # (feedback.jsonl), the expert's text is the ground truth for
    # what the agent SHOULD have produced. The judge uses this for
    # near-direct comparison rather than soft rubric scoring.
    expert_correction: str = ""


@dataclass
class CandidateEdit:
    """One proposal from the optimizer. Bounded by design — see the
    optimizer prompt below for the exact JSON contract."""
    kind: str                                  # "add" | "delete" | "replace"
    rationale: str = ""                        # one-liner from the optimizer
    section: str = ""                          # markdown heading or "" for end-of-file
    content: str = ""                          # new text (for add / replace)
    target_text: str = ""                      # text being replaced/deleted (must match)


@dataclass
class EvolveResult:
    """Returned from one round of evolve_skill_once."""
    accepted: bool
    before_score: float
    after_score: float
    edit: Optional[CandidateEdit] = None
    new_body: str = ""
    iterations_tried: int = 0
    rejected_reasons: list[str] = field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────
# Scoring (judge-LLM rubric over examples)
# ─────────────────────────────────────────────────────────────────────


JUDGE_PROMPT = """You are a strict but fair grader. Given an agent's
output and a rubric describing what "good" looks like, return ONE
JSON object — no prose around it — with shape:

  {"score": 0-100, "issues": ["short issue 1", ...]}

The score is on a 0-100 scale. 100 = perfectly matches the rubric.
0 = completely fails. Be calibrated:
  - 80+ : clear pass, only minor polish issues
  - 60-79: usable but has 1-2 important gaps
  - 40-59: partial, missing key requirements
  - <40 : fails core intent
"""


async def score_skill_on_examples(
    skill_body: str,
    examples: list[TaskExample],
    *,
    target_model: Optional[str] = None,
    judge_model: Optional[str] = None,
    llm_caller: Optional[Callable] = None,
) -> tuple[float, list[dict]]:
    """Run each example through the skill, judge the output, return
    (mean_score, per_example_details).

    ``llm_caller`` lets tests inject a fake. In production we call
    nexus_server.llm_gateway.call_llm.
    """
    if not examples:
        return 0.0, []

    if llm_caller is None:
        from nexus_server.llm_gateway import call_llm as _call
        async def llm_caller(messages, system_prompt, model, **kwargs):
            content, model_used, _stop, _tools = await _call(
                messages=messages, system_prompt=system_prompt,
                model=model, temperature=None,
                max_tokens=kwargs.get("max_tokens", 4096), tools=None,
            )
            return content

    details: list[dict] = []
    total = 0.0
    for ex in examples:
        # Step 1: run the skill on the example input.
        # #131 — when the example has images, attach them as vision
        # parts on the rollout message. The SDK's
        # _messages_to_gemini_contents (since #123) auto-converts to
        # inline_data Blob parts when the message dict carries an
        # ``images`` key.
        rollout_msg: dict = {"role": "user", "content": ex.input}
        if ex.images:
            rollout_msg["images"] = list(ex.images)
        try:
            output = await llm_caller(
                messages=[rollout_msg],
                system_prompt=skill_body,
                model=target_model,
            )
        except Exception as e:  # noqa: BLE001
            logger.warning("score: skill rollout failed: %s", e)
            details.append({"input": ex.input[:80], "score": 0.0,
                            "issues": [f"rollout failed: {e}"]})
            continue

        # Step 2: judge the output against the rubric.
        rubric_block = (
            f"\n\nRubric:\n{ex.rubric}" if ex.rubric else ""
        )
        ref_block = (
            f"\n\nReference output summary:\n{ex.expected_output_summary}"
            if ex.expected_output_summary else ""
        )
        # #131 — when this example came from a real medic correction,
        # the expert's text is the highest-priority ground truth.
        # Tell the judge to weight closeness to the correction
        # heavily rather than fuzzy rubric matching.
        correction_block = ""
        if ex.expert_correction:
            correction_block = (
                f"\n\nEXPERT CORRECTION (ground truth — score "
                f"based on closeness to this; agents that ignore "
                f"the correction lose heavily):\n{ex.expert_correction}"
            )
        judge_user = (
            f"AGENT OUTPUT:\n```\n{output}\n```\n"
            f"INPUT THAT GENERATED IT:\n```\n{ex.input}\n```"
            f"{rubric_block}{ref_block}{correction_block}\n\n"
            "Return your JSON verdict now."
        )
        # Pass image bytes to the judge too — judge needs to see the
        # actual visual content to know whether the agent's claim is
        # consistent with what's visible.
        judge_msg: dict = {"role": "user", "content": judge_user}
        if ex.images:
            judge_msg["images"] = list(ex.images)
        try:
            verdict_raw = await llm_caller(
                messages=[judge_msg],
                system_prompt=JUDGE_PROMPT,
                model=judge_model,
            )
        except Exception as e:  # noqa: BLE001
            logger.warning("score: judge call failed: %s", e)
            details.append({"input": ex.input[:80], "score": 0.0,
                            "issues": [f"judge failed: {e}"]})
            continue

        score, issues = _parse_verdict(verdict_raw)
        total += score
        details.append({
            "input": ex.input[:80],
            "output_preview": (output or "")[:200],
            "score": score,
            "issues": issues,
        })

    mean = total / max(1, len(examples))
    return mean, details


def _parse_verdict(raw: str) -> tuple[float, list[str]]:
    """Be forgiving — LLMs love to wrap JSON in fences."""
    if not raw:
        return 0.0, ["empty verdict"]
    # Try to find a JSON object inside (handles ```json ... ```).
    m = re.search(r"\{[\s\S]*\}", raw)
    if not m:
        return 0.0, [f"verdict has no JSON: {raw[:80]}"]
    try:
        obj = json.loads(m.group(0))
    except json.JSONDecodeError as e:
        return 0.0, [f"verdict not valid JSON: {e}"]
    try:
        score = float(obj.get("score", 0))
    except (ValueError, TypeError):
        score = 0.0
    issues = obj.get("issues") or []
    if not isinstance(issues, list):
        issues = [str(issues)]
    return max(0.0, min(100.0, score)), [str(i) for i in issues[:10]]


# ─────────────────────────────────────────────────────────────────────
# Edit application (bounded)
# ─────────────────────────────────────────────────────────────────────


def apply_edit(body: str, edit: CandidateEdit) -> Optional[str]:
    """Apply one bounded edit to ``body``. Returns the new body or
    ``None`` if the edit's target text wasn't found (we never invent
    a location — bad targets reject)."""
    if edit.kind == "add":
        if edit.section:
            # Insert just after the heading (## / ### / etc.).
            heading_re = re.compile(
                rf"^(#{{1,6}}\s+{re.escape(edit.section)}\s*)$",
                re.MULTILINE,
            )
            m = heading_re.search(body)
            if not m:
                # No matching heading — append to end of body.
                return body.rstrip() + f"\n\n{edit.content.rstrip()}\n"
            insert_at = m.end()
            return body[:insert_at] + "\n\n" + edit.content.rstrip() + body[insert_at:]
        # No section — append at end.
        return body.rstrip() + f"\n\n{edit.content.rstrip()}\n"

    if edit.kind == "replace":
        if not edit.target_text or edit.target_text not in body:
            return None  # target not found — refuse to "find a close match"
        return body.replace(edit.target_text, edit.content, 1)

    if edit.kind == "delete":
        if not edit.target_text or edit.target_text not in body:
            return None
        return body.replace(edit.target_text, "", 1)

    return None


# ─────────────────────────────────────────────────────────────────────
# Optimizer LLM call (propose bounded edits)
# ─────────────────────────────────────────────────────────────────────


OPTIMIZER_PROMPT = """You are a skill-document optimizer. The user
runs an agent under a SKILL.md prompt. We just ran it on held-out
examples and observed the agent's outputs + judge scores.

Your job: propose at most THREE bounded edits to SKILL.md that make
the agent score higher on the held-out set on the NEXT run.

You MUST output ONE JSON object — no prose around it — with shape:

  {
    "edits": [
      {
        "kind":        "add" | "delete" | "replace",
        "rationale":   "<one short sentence>",
        "section":     "<markdown heading, only for 'add'>",
        "target_text": "<exact text to delete/replace — must match SKILL.md verbatim>",
        "content":     "<new text for add/replace>"
      },
      ...
    ]
  }

Hard rules:
  1. NEVER touch the durable region. It's not shown to you (replaced
     by <<<NEXUS_DURABLE_N>>> placeholders). Treat those tokens as
     immovable; do NOT delete or replace them.
  2. For "replace" or "delete", `target_text` MUST appear verbatim
     in the editable body. If you guess and miss, the edit is
     rejected and the run wastes a round.
  3. Bounded: at most 3 edits. Quality > quantity. If you can fix
     the worst issue with ONE edit, output one and stop.
  4. Each edit should address a concrete issue from the judges'
     feedback — not aesthetic preferences. Cite the issue in
     `rationale`.
  5. Do NOT propose edits identical to ones in the `previously_rejected`
     list below — they've already been validated and rejected.

When in doubt, prefer ADDing a clarifying rule over REPLACEing
existing text. Adds are recoverable; replaces destroy info.
"""


async def propose_edits(
    *,
    editable_body: str,
    judge_details: list[dict],
    previously_rejected: list[dict],
    optimizer_model: Optional[str] = None,
    llm_caller: Optional[Callable] = None,
) -> list[CandidateEdit]:
    """Ask the optimizer LLM to propose up to 3 bounded edits."""
    if llm_caller is None:
        from nexus_server.llm_gateway import call_llm as _call
        async def llm_caller(messages, system_prompt, model, **kwargs):
            content, _m, _s, _t = await _call(
                messages=messages, system_prompt=system_prompt,
                model=model, temperature=None, max_tokens=4096, tools=None,
            )
            return content

    issues_block = "\n".join(
        f"- ex#{i+1} score={d.get('score', 0):.0f}: "
        f"{', '.join(d.get('issues') or []) or '(no issues reported)'}"
        for i, d in enumerate(judge_details)
    ) or "(no examples scored)"

    rejected_block = ""
    if previously_rejected:
        rejected_block = (
            "\n\nPreviously rejected edits (do NOT repropose):\n"
            + "\n".join(
                f"- {r.get('kind', '?')}: {r.get('rationale', '')[:80]} "
                f"→ reason: {r.get('reason', 'no score improvement')[:80]}"
                for r in previously_rejected[-10:]   # last 10 only
            )
        )

    user_msg = (
        f"Current SKILL.md editable body:\n```\n{editable_body}\n```\n\n"
        f"Judge feedback from {len(judge_details)} examples:\n"
        f"{issues_block}\n"
        f"{rejected_block}\n\n"
        "Propose your edits now as JSON."
    )

    try:
        raw = await llm_caller(
            messages=[{"role": "user", "content": user_msg}],
            system_prompt=OPTIMIZER_PROMPT,
            model=optimizer_model,
        )
    except Exception as e:  # noqa: BLE001
        logger.warning("optimizer call failed: %s", e)
        return []

    return _parse_proposal(raw)


def _parse_proposal(raw: str) -> list[CandidateEdit]:
    m = re.search(r"\{[\s\S]*\}", raw or "")
    if not m:
        return []
    try:
        obj = json.loads(m.group(0))
    except json.JSONDecodeError:
        return []
    edits_raw = obj.get("edits") or []
    if not isinstance(edits_raw, list):
        return []
    out: list[CandidateEdit] = []
    for e in edits_raw[:3]:                 # bounded — at most 3
        if not isinstance(e, dict):
            continue
        kind = str(e.get("kind", "")).strip().lower()
        if kind not in ("add", "delete", "replace"):
            continue
        out.append(CandidateEdit(
            kind=kind,
            rationale=str(e.get("rationale", "")).strip()[:300],
            section=str(e.get("section", "")).strip()[:200],
            content=str(e.get("content", "")),
            target_text=str(e.get("target_text", "")),
        ))
    return out


# ─────────────────────────────────────────────────────────────────────
# Rejected-edit buffer (sidecar .rejected.jsonl)
# ─────────────────────────────────────────────────────────────────────


def _rejected_buffer_path(skill_dir: Path) -> Path:
    return skill_dir / ".rejected.jsonl"


def load_rejected_buffer(skill_dir: Path) -> list[dict]:
    p = _rejected_buffer_path(skill_dir)
    if not p.exists():
        return []
    out: list[dict] = []
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return out


def append_rejected(skill_dir: Path, edit: CandidateEdit, reason: str) -> None:
    p = _rejected_buffer_path(skill_dir)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("a", encoding="utf-8") as f:
        f.write(json.dumps({
            "kind":        edit.kind,
            "section":     edit.section,
            "target_text": edit.target_text[:200],
            "content":     edit.content[:200],
            "rationale":   edit.rationale[:200],
            "reason":      reason[:200],
        }) + "\n")


# ─────────────────────────────────────────────────────────────────────
# The core loop — strictly-improve gate
# ─────────────────────────────────────────────────────────────────────


async def evolve_skill_once(
    *,
    skill_body: str,
    skill_dir: Optional[Path],
    examples: list[TaskExample],
    target_model: Optional[str] = None,
    optimizer_model: Optional[str] = None,
    judge_model: Optional[str] = None,
    current_score: Optional[float] = None,
    llm_caller: Optional[Callable] = None,
) -> EvolveResult:
    """One propose → score → gate cycle.

    Returns an :class:`EvolveResult`. If ``accepted=True``,
    ``new_body`` is the post-edit SKILL.md (with durable regions
    re-fenced) and ``after_score > before_score`` strictly.
    """
    from nexus_core.skills.manager import (
        extract_durable_regions,
        reweave_durable,
    )

    # Score the current skill if the caller didn't precompute.
    if current_score is None:
        current_score, current_details = await score_skill_on_examples(
            skill_body, examples,
            target_model=target_model, judge_model=judge_model,
            llm_caller=llm_caller,
        )
    else:
        # Need the per-example details anyway for the optimizer prompt.
        _, current_details = await score_skill_on_examples(
            skill_body, examples,
            target_model=target_model, judge_model=judge_model,
            llm_caller=llm_caller,
        )

    durable_blocks, editable_body = extract_durable_regions(skill_body)
    rejected = load_rejected_buffer(skill_dir) if skill_dir else []

    proposals = await propose_edits(
        editable_body=editable_body,
        judge_details=current_details,
        previously_rejected=rejected,
        optimizer_model=optimizer_model or target_model,
        llm_caller=llm_caller,
    )
    if not proposals:
        return EvolveResult(
            accepted=False,
            before_score=current_score,
            after_score=current_score,
            iterations_tried=0,
            rejected_reasons=["optimizer proposed no edits"],
        )

    # Try edits in order. Strict-improve gate: first one that
    # beats the current score becomes the new best; others are
    # logged as rejected.
    rejected_this_round: list[str] = []
    for idx, edit in enumerate(proposals):
        candidate_editable = apply_edit(editable_body, edit)
        if candidate_editable is None:
            reason = "target_text not found in body"
            rejected_this_round.append(f"edit#{idx}: {reason}")
            if skill_dir:
                append_rejected(skill_dir, edit, reason)
            continue
        # Re-thread durable blocks before scoring (so the agent
        # actually sees them at execution).
        candidate_full = reweave_durable(candidate_editable, durable_blocks)
        cand_score, _details = await score_skill_on_examples(
            candidate_full, examples,
            target_model=target_model, judge_model=judge_model,
            llm_caller=llm_caller,
        )
        if cand_score > current_score:
            return EvolveResult(
                accepted=True,
                before_score=current_score,
                after_score=cand_score,
                edit=edit,
                new_body=candidate_full,
                iterations_tried=idx + 1,
                rejected_reasons=rejected_this_round,
            )
        reason = f"score {cand_score:.1f} did not beat current {current_score:.1f}"
        rejected_this_round.append(f"edit#{idx}: {reason}")
        if skill_dir:
            append_rejected(skill_dir, edit, reason)

    return EvolveResult(
        accepted=False,
        before_score=current_score,
        after_score=current_score,
        iterations_tried=len(proposals),
        rejected_reasons=rejected_this_round,
    )


async def evolve_skill_loop(
    *,
    skill_body: str,
    skill_dir: Optional[Path],
    examples: list[TaskExample],
    target_model: Optional[str] = None,
    optimizer_model: Optional[str] = None,
    judge_model: Optional[str] = None,
    max_iterations: int = 3,
    llm_caller: Optional[Callable] = None,
) -> dict[str, Any]:
    """Repeat evolve_skill_once until no improvement OR max_iterations.

    Returns a summary dict for UI rendering: before/after scores, the
    list of accepted edits with rationale, the final SKILL.md body."""
    if not examples:
        return {
            "status":         "no_examples",
            "before_score":   0.0,
            "after_score":    0.0,
            "accepted_edits": [],
            "final_body":     skill_body,
            "iterations":     0,
        }
    initial_score, _ = await score_skill_on_examples(
        skill_body, examples,
        target_model=target_model, judge_model=judge_model,
        llm_caller=llm_caller,
    )
    body = skill_body
    accepted: list[dict] = []
    rejected_summary: list[str] = []
    cur = initial_score
    for it in range(max_iterations):
        result = await evolve_skill_once(
            skill_body=body, skill_dir=skill_dir,
            examples=examples,
            target_model=target_model,
            optimizer_model=optimizer_model,
            judge_model=judge_model,
            current_score=cur,
            llm_caller=llm_caller,
        )
        rejected_summary.extend(result.rejected_reasons)
        if not result.accepted:
            break
        accepted.append({
            "iteration":   it + 1,
            "kind":        result.edit.kind if result.edit else "",
            "rationale":   result.edit.rationale if result.edit else "",
            "delta":       result.after_score - result.before_score,
            "after_score": result.after_score,
        })
        body = result.new_body
        cur  = result.after_score
    return {
        "status":           "ok",
        "before_score":     initial_score,
        "after_score":      cur,
        "accepted_edits":   accepted,
        "rejected_reasons": rejected_summary[:50],
        "final_body":       body,
        "iterations":       len(accepted),
    }


# ─────────────────────────────────────────────────────────────────────
# #131 — Feedback ⇒ TaskExample loader
# ─────────────────────────────────────────────────────────────────────


def build_examples_from_feedback(
    feedback_path: Path,
    *,
    user_id: Optional[str] = None,
    max_examples: int = 20,
) -> list[TaskExample]:
    """Convert a skill's feedback.jsonl into held-out TaskExamples
    that ``evolve_skill_loop`` can score against.

    Reads ``feedback.jsonl`` (written by the #130 endpoint), one row
    per medic gesture:

      * ``kind="correct"`` rows produce a TaskExample with
        ``expert_correction`` set to the medic's text. The judge then
        scores how close the agent's NEW output is to the correction.
      * ``kind="accept"`` rows are positive samples; we record them
        with the original agent output as ``expected_output_summary``
        so the judge knows what "still good" looks like — the
        evolver shouldn't regress on what was already accepted.

    When ``user_id`` is provided, we also try to hydrate image bytes
    from the uploads table for each ``referenced_file_ids`` entry,
    so vision-capable judge models can re-look at the actual image.
    Failures here are silent — the example simply has empty images
    and falls back to text-only judging.

    Caps at ``max_examples`` (newest-first) so a long feedback log
    doesn't blow out the evolver's per-example LLM round-trip budget.
    """
    if not feedback_path.exists():
        return []

    rows: list[dict] = []
    try:
        for line in feedback_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    except Exception as e:  # noqa: BLE001
        logger.warning("feedback load failed for %s: %s", feedback_path, e)
        return []

    # Newest-first — feedback is appended chronologically, so reverse.
    rows = list(reversed(rows))[:max_examples]

    # Image hydration: optional lookup table. We try a few common
    # storage backends; missing bytes just leave images empty so
    # the example is still usable as text-only.
    def _load_image_bytes(file_ids: list[str]) -> list[dict]:
        if not file_ids or not user_id:
            return []
        try:
            from nexus_server import files as _files
        except ImportError:
            return []
        out: list[dict] = []
        try:
            resolved = _files.resolve_files(user_id, file_ids)
        except Exception as e:  # noqa: BLE001
            logger.debug("image hydration failed: %s", e)
            return []
        import base64 as _b64
        for r in resolved:
            mime = r.get("mime") or ""
            if not mime.startswith("image/"):
                continue
            disk = r.get("disk_path")
            if not disk:
                continue
            try:
                raw = _files.read_file_bytes(disk)
            except Exception:  # noqa: BLE001
                raw = None
            if raw is None:
                continue
            out.append({
                "mime": mime,
                "data_b64": _b64.b64encode(raw).decode("ascii"),
            })
        return out

    examples: list[TaskExample] = []
    for r in rows:
        ctx = r.get("context") or {}
        fb = r.get("feedback") or {}
        kind = (r.get("kind") or fb.get("kind") or "").strip()
        agent_output = ctx.get("agent_output") or ""
        ref_ids = ctx.get("referenced_file_ids") or []
        # The "input" for the example is whatever the agent ran on.
        # For now we don't have a verbatim copy of the bare user
        # message (we'd need to also stamp it on the assistant_response
        # metadata). Use a synthetic prompt: "look at the attached
        # image" — close enough since the image is the real input.
        if isinstance(ref_ids, list) and ref_ids:
            ex_input = (
                "Please analyse the attached image and report findings "
                "following your standard protocol."
            )
        else:
            ex_input = (
                "Please respond to the following user query. Apply your "
                "standard protocol."
            )

        images = _load_image_bytes(ref_ids if isinstance(ref_ids, list) else [])

        if kind == "correct":
            examples.append(TaskExample(
                input=ex_input,
                images=images,
                expert_correction=(fb.get("expert_text") or "").strip(),
                rubric=(
                    "Score how closely the agent's output incorporates "
                    "the expert correction. Outputs that ignore the "
                    "correction lose heavily. Outputs that mention the "
                    "correction but still draw the wrong conclusion get "
                    "partial credit."
                ),
            ))
        elif kind == "accept":
            # Positive sample — record the accepted agent output as
            # the reference. The evolver shouldn't regress against
            # responses that were already approved.
            examples.append(TaskExample(
                input=ex_input,
                images=images,
                expected_output_summary=agent_output[:1500],
                rubric=(
                    "This output was previously accepted by the expert. "
                    "Score how closely the new agent output preserves "
                    "the structure and key findings. Don't penalise "
                    "minor phrasing differences; do penalise regressions "
                    "(missing findings, weakened recommendations)."
                ),
            ))

    return examples
